pipeline {
  agent any

  environment {
    AWS_REGION     = "us-west-2"
    AWS_ACCOUNT_ID = "070938122390"  
    ECR_REPO_NAME  = "lesson-8-9-django-ecr"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Push Docker image') {
      steps {
        sh '''
          set -e

          IMAGE_TAG=build-${BUILD_NUMBER}
          REMOTE_REPO=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}

          echo "Login to ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

          echo "Build image..."
          docker build -t ${ECR_REPO_NAME}:${IMAGE_TAG} .

          echo "Tag image for ECR..."
          docker tag ${ECR_REPO_NAME}:${IMAGE_TAG} ${REMOTE_REPO}:${IMAGE_TAG}

          echo "Push image..."
          docker push ${REMOTE_REPO}:${IMAGE_TAG}

          echo "Update Helm values.yaml with new tag..."
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" lesson-8-9/charts/django-app/values.yaml
        '''
      }
    }

    stage('Commit & Push changes') {
      steps {
        sh '''
          set -e

          git config user.name "Jenkins"
          git config user.email "jenkins@example.com"

          git add lesson-8-9/charts/django-app/values.yaml || true
          git commit -m "Update image tag from Jenkins" || echo "No changes to commit"

          git push origin lesson-8-9
        '''
      }
    }
  }
}
